"""New Migration

Revision ID: 60e73be051f2
Revises: fcef7880549d
Create Date: 2022-12-04 17:49:39.930322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e73be051f2'
down_revision = 'fcef7880549d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
