"""New Migration

Revision ID: fcef7880549d
Revises: 387b2c74bb25
Create Date: 2022-12-04 17:48:52.624779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcef7880549d'
down_revision = '387b2c74bb25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
