version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    environment:
      DB_HOST: db
    links:
      - db
    volumes:
      - shared:/buckets/tasks

  # async:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app/Dockerfile
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   expose:
  #     - 8000
  #   environment:
  #     DB_HOST: db
  #     ASYNC: 1
  #   links:
  #     - db
  #   volumes:
  #     - type: volume
  #       source: shared
  #       target: /buckets/tasks
  
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "8000:8000"
    

volumes:
  shared: