version: "3.7"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admins
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
  
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    environment:
      DB_HOST: db
      ENDPOINT: minio:9000
    links:
      - db
      - minio

  async:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    environment:
      DB_HOST: db
      ASYNC: 1
      ENDPOINT: minio:9000
    links:
      - db
      - minio

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "8000:8000"


# volumes:
#   shared:
volumes:
  minio_storage: